### ISSUE TITLE
Potential memory leaks in error cases

### ISSUE THREAD

**Issue by AlaynaMonteiro** [acmpesuecc/grade-card#1]
The program doesn't free allocated memory when errors occur (like file operations) or when the user inputs invalid data. This could lead to memory leaks.

- Clean up the memory when errors occurs while reading and writing to the file
- Clean up the memory if scanf() operations fail
- Implement a cleanup function to deallocate memory in a centralized manner

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by AlaynaMonteiro** [comment]
!assign @aniruddhajoshi100

**Comment by atharv24mittal** [comment]
can i get it assigned ?

**Comment by MKD2004** [comment]
can i get it assigned?

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by PES2UG23CS075** [comment]
can i get assigned

**Comment by AnshulBanda** [comment]
can i get it assigned to me ?

**Comment by Lalith2907** [comment]
can you assign me this pls

**Comment by DhruvHegde** [comment]
can you assign me this please

**Comment by AlaynaMonteiro** [comment]
!deassign
