### ISSUE TITLE
Make student data persistent between operations

### ISSUE THREAD

**Issue by AlaynaMonteiro** [acmpesuecc/grade-card#2]
In the current implementation structure, the student records are not maintained properly. If the list of new students is updated, then all the previously entered data gets erased. The CSV file gets overwritten instead of appended when multiple student records are saved and there is no option to view all the saved student records.

- Append new student data while maintaining all student data (previous ones in the same session too)
- Function to view the records
- Function to modify any existing record

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by AkshayaR11** [comment]
can i get this assigned to me?

**Comment by Gunika-Goel** [comment]
can i get this assigned to me?

**Comment by Anyaaa-2** [comment]
can i get assigned

**Comment by Asritha916** [comment]
can i be assigned for the issue

**Comment by AutisticCoder-9000** [comment]
Can I get assigned?

**Comment by unrelatedchase34** [comment]
can i get this assigned

**Comment by madhavkbinoy** [comment]
can I get assigned

**Comment by AlaynaMonteiro** [comment]
!assign @AkshayaR11 60

**Comment by AlaynaMonteiro** [comment]
!assign @Anyaaa-2 60

**Comment by AlaynaMonteiro** [comment]
!assign @Asritha916 60

**Comment by AlaynaMonteiro** [comment]
!assign @AutisticCoder-9000 60

**Comment by AlaynaMonteiro** [comment]
!assign @unrelatedchase34 60

**Comment by AlaynaMonteiro** [comment]
!assign @madhavkbinoy 60

**Comment by ghost** [comment]
can i get this assigned

**Comment by SamarthRamesha** [comment]
pls assign this to me

**Comment by Shaynazg** [comment]
Can I pls be assigned?

**Comment by KaparthyReddy** [comment]
kindly assign this.

**Comment by Peeyushhhhh** [comment]
can I pls get assigned

**Comment by AutisticCoder-9000** [comment]
May I kindly get a 10-15 minute extension?

**Comment by Anyaaa-2** [comment]
can u assign this to me

**Comment by madhavkbinoy** [comment]
can I get a 15 minute extension?

**Comment by AnshulBanda** [comment]
can i get this assigned to me ?

**Comment by PES2UG23CS075** [comment]
can i get assigned

**Comment by AyushChakraborty** [comment]
please assign this to me

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by devanshishukla17** [comment]
can I get assigned to this?

**Comment by AlaynaMonteiro** [comment]
!assign @Satvik-max33

**Comment by AlaynaMonteiro** [comment]
!assign @SamarthRamesha

**Comment by AlaynaMonteiro** [comment]
!assign @Shaynazg

**Comment by Anyaaa-2** [comment]
can you please assign this to me

**Comment by KaparthyReddy** [comment]
could u assign this

**Comment by AutisticCoder-9000** [comment]
!deassign

**Comment by AlaynaMonteiro** [comment]
@Shaynazg I'd like to know your progress

**Comment by AlaynaMonteiro** [comment]
@Shaynazg There has been no response from you and so I shall deassign you

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by KaparthyReddy** [comment]
kindly assign this

**Comment by KaparthyReddy** [comment]
kindly assign.
