### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by AlaynaMonteiro** [acmpesuecc/grade-card#4]
Implement a function to search students by roll number, marks, or semester

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by amankhandelwaal** [comment]
hi, please assign!

**Comment by stealthwhizz** [comment]
can i get this assigned?

**Comment by Aditya-C-S** [comment]
can u please assign #4

**Comment by Shaynazg** [comment]
Can I get this assigned?

**Comment by AlaynaMonteiro** [comment]
!assign @amankhandelwaal

**Comment by thisisselva18** [comment]
Can I get this assigned?

**Comment by Greninja44** [comment]
can i get assigned

**Comment by SanjoliT** [comment]
can i get assigned

**Comment by Gunika-Goel** [comment]
can i please get assigned?

**Comment by AlaynaMonteiro** [comment]
```
bash
functions.c: In function ‘search’:
functions.c:287:13: error: implicit declaration of function ‘search_rollno’; did you mean ‘search_roll_no’? [-Wimplicit-function-declaration]
  287 |             search_rollno(stu, n);
      |             ^~~~~~~~~~~~~
      |             search_roll_no
functions.c: At top level:
functions.c:303:6: error: conflicting types for ‘search_rollno’; have ‘void(student *, int)’ [-Werror]
  303 | void search_rollno(student *stu, int n)
      |      ^~~~~~~~~~~~~
functions.c:287:13: note: previous implicit declaration of ‘search_rollno’ with type ‘void(student *, int)’
  287 |             search_rollno(stu, n);
      |             ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:15: functions.o] Error 1
```
@amankhandelwaal Fix these issues

**Comment by AlaynaMonteiro** [comment]
!deassign @amankhandelwaal

**Comment by AlaynaMonteiro** [comment]
!assign @amankhandelwaal 60

**Comment by amankhandelwaal** [comment]
hey, i was out for dinner. Just saw the mentions. Kindly extend the time by a bit once it de-assigns.

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by avinash-selvan** [comment]
Can you assign it to me?

**Comment by SamridhiShreyaa** [comment]
can i be assigned this issue?

**Comment by AlaynaMonteiro** [comment]
@amankhandelwaal It only displays the first record having the roll number, sem or marks to be searched for instead of displaying all of them. The search_rollno and search_marks functions also contain segfaults and the search_semester function does not always display the records. Partial points will be assigned

**Comment by AlaynaMonteiro** [comment]
!assign @avinaldo22 60

**Comment by AlaynaMonteiro** [comment]
!assign @SamridhiShreyaa

**Comment by amankhandelwaal** [comment]
@AlaynaMonteiro you just now told that you are assigning it to me

**Comment by SamridhiShreyaa** [comment]
@AlaynaMonteiro  am i assigned to this issue? In the assign it's not showing me

**Comment by AlaynaMonteiro** [comment]
@SamridhiShreyaa you are not assigned to this issue

**Comment by AlaynaMonteiro** [comment]
@avinaldo22 what's your progress so far?  Please let me know which sem hall you're in

**Comment by AyushChakraborty** [comment]
please assign as it shows no one is assigned to it

**Comment by shreyasoni26** [comment]
can i please be assigned

**Comment by AlaynaMonteiro** [comment]
!assign @amankhandelwaal 60

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by AlaynaMonteiro** [comment]
!assign @amankhandelwaal 60

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by anirudhsudhir** [comment]
!assign @amankhandelwaal 60

**Comment by AlaynaMonteiro** [comment]
!assign @amankhandelwaal 45

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by bwaklog** [comment]
!assign @amankhandelwaal 45

**Comment by bwaklog** [comment]
@amankhandelwaal you are free to work on this issue

**Comment by AlaynaMonteiro** [comment]
@amankhandelwaal I am expecting acceptable progress in the given 45 minutes, please make sure you use it to the rightest, after that i will have to deassign, All The Best....

**Comment by amankhandelwaal** [comment]
@bwaklog @AlaynaMonteiro thankyou

**Comment by amankhandelwaal** [comment]
@AlaynaMonteiro i have made a PR, kindly review it asap and lmk if those issues still exist

**Comment by amankhandelwaal** [comment]
@bwaklog

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by SamridhiShreyaa** [comment]
can i be assigned?

**Comment by Gunika-Goel** [comment]
can i be assigned this please?

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by H-Mudliar** [comment]
Can I be assigned to this?

**Comment by AnshulBanda** [comment]
can i get this assigned?

**Comment by jmanoj0905** [comment]
Can I get assigned please

**Comment by AlaynaMonteiro** [comment]
!assign @stealthwhizz

**Comment by AlaynaMonteiro** [comment]
!assign @Aditya-C-S

**Comment by Aditya-C-S** [comment]
@AlaynaMonteiro i finished adding the search feature
now i will send a pull request

**Comment by DHANUVARSHA04** [comment]
Can you assign me this qsn ?

**Comment by DHANUVARSHA04** [comment]
@AlaynaMonteiro Can you assign me this qsn thank you

**Comment by ghost** [comment]
Can you please assign this qsn to me ? Thank you

**Comment by H-Mudliar** [comment]
Can I be assigned

**Comment by AlaynaMonteiro** [comment]
!deassign
