### ISSUE TITLE
Sort feature

### ISSUE THREAD

**Issue by AlaynaMonteiro** [acmpesuecc/grade-card#5]
Implement a feature to sort students by SGPA, name or roll number.

**Comment by MKD2004** [comment]
Can i be assigned?

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by Greninja44** [comment]
can i get assigned

**Comment by gma4040** [comment]
can I get assigned ?

**Comment by Shaynazg** [comment]
can i get assigned?

**Comment by AlaynaMonteiro** [comment]
!assign @MKD2004

**Comment by thisisselva18** [comment]
Can I get assigned?

**Comment by thisisselva18** [comment]
Can I get this assigned?

**Comment by Neonishh** [comment]
Can I get assigned?

**Comment by MKD2004** [comment]
> !assign @MKD2004

I will be going for dinner,please compensate for my time. Thank you

**Comment by aniruddhajoshi100** [comment]
can I pls get this assigned?

**Comment by AlaynaMonteiro** [comment]
!deassign @aniruddhajoshi100

**Comment by AlaynaMonteiro** [comment]
!assign @aniruddhajoshi100 60

**Comment by madhavkbinoy** [comment]
can I get assigned

**Comment by Peeyushhhhh** [comment]
Can I get assigned

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by AlaynaMonteiro** [comment]
!assign @MKD2004 60

**Comment by AlaynaMonteiro** [comment]
!assign @MKD2004 60

**Comment by Shaynazg** [comment]
Can I pls be assigned?

**Comment by sherlockhome12** [comment]
can i get assigned ??

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by ghost** [comment]
can i get assgined

**Comment by Ruchavw** [comment]
can i get assigned

**Comment by SamridhiShreyaa** [comment]
can i get assigned?

**Comment by Gunika-Goel** [comment]
can i get assigned please?

**Comment by H-Mudliar** [comment]
Can i be assigned

**Comment by AnshulBanda** [comment]
can i get this assigned ?

**Comment by ghost** [comment]
> can i get assgined

can i get it assigned

**Comment by jmanoj0905** [comment]
Can I get assigned please

**Comment by Peeyushhhhh** [comment]
can i get assigned

**Comment by ghost** [comment]
please can i be assigned

**Comment by AlaynaMonteiro** [comment]
!assign @aakanksha-p-3

**Comment by AlaynaMonteiro** [comment]
!assign @Ruchavw

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by AlaynaMonteiro** [comment]
!assign @madhavkbinoy 30

**Comment by aakanksha-p-3** [comment]
> !deassign

can i be assigned back im all most done

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by aakanksha-p-3** [comment]
pleas assign to me im alomost done


> !deassign

pleas assign to me im all most done

**Comment by AlaynaMonteiro** [comment]
Alright, I shall do so

**Comment by ghost** [comment]
please assign to me

**Comment by AlaynaMonteiro** [comment]
!assign @aakanksha-p-3 60

**Comment by H-Mudliar** [comment]
Can I be assigned

**Comment by H-Mudliar** [comment]
Can I be assigned

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by H-Mudliar** [comment]
Can I be assigned
